name: Frontend CI
on:
  push:
    branches:
      - master

  pull_request:
    branches: ['**']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install packages
        run: npm run install:prod:full

      - name: Lint
        run: npm run eslint && npm run stylelint && npm run svelte:check

      - name: Icons
        run: npm run fontello

      - name: Environment
        run: cp template.env .env

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test:prod

  publish:
    if: github.ref == 'refs/heads/master'
    name: Deployment
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: ${{ secrets.NPM_REGISTRY_URL }}
          scope: ${{ secrets.NPM_PACKAGE_SCOPE }}

      - name: Install packages
        run: npm ci

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_WRITE_TOKEN }}
